<?php

return [
    'PbApp\Request'=>[
        'Headers'=>[
            'IsScalarType'=>true,
            'FieldType'=>'string', 
            'IsArray'=>false, 
            'IsMap'=>true, 
            'MapKeyType'=>'string'
        ],

        'BodyParams'=>[
            'IsScalarType'=>true,
            'FieldType'=>'string', 
            'IsArray'=>false, 
            'IsMap'=>true, 
            'MapKeyType'=>'string'
        ],
    ],
    'PbApp\Meta'=>[
        'Param1'=>[
            'IsScalarType'=>true,
            'FieldType'=>'int32', 
            'IsArray'=>false, 
            'IsMap'=>false, 
            'MapKeyType'=>'null'
        ],
    ],
    'PbApp\Reponse'=>[
        'ReflectClass'=>[
            'IsScalarType'=>true,
            'FieldType'=>'string', 
            'IsArray'=>false, 
            'IsMap'=>false, 
            'MapKeyType'=>'null'
        ],

        'Body'=>[
            'IsScalarType'=>true,
            'FieldType'=>'bytes', 
            'IsArray'=>false, 
            'IsMap'=>false, 
            'MapKeyType'=>'null'
        ],

        'ArrayParams'=>[
            'IsScalarType'=>true,
            'FieldType'=>'string', 
            'IsArray'=>true, 
            'IsMap'=>false, 
            'MapKeyType'=>'null'
        ],

        'MapParams'=>[
            'IsScalarType'=>false,
            'FieldType'=>'PbApp\Meta', 
            'IsArray'=>false, 
            'IsMap'=>true, 
            'MapKeyType'=>'string'
        ],
    ],
    'PbApp\UserInfo'=>[
        'OpenUid'=>[
            'IsScalarType'=>true,
            'FieldType'=>'string', 
            'IsArray'=>false, 
            'IsMap'=>false, 
            'MapKeyType'=>'null'
        ],

        'NickName'=>[
            'IsScalarType'=>true,
            'FieldType'=>'string', 
            'IsArray'=>false, 
            'IsMap'=>false, 
            'MapKeyType'=>'null'
        ],

        'Age'=>[
            'IsScalarType'=>true,
            'FieldType'=>'int32', 
            'IsArray'=>false, 
            'IsMap'=>false, 
            'MapKeyType'=>'null'
        ],

        'Param1'=>[
            'IsScalarType'=>true,
            'FieldType'=>'int32', 
            'IsArray'=>false, 
            'IsMap'=>false, 
            'MapKeyType'=>'null'
        ],
    ],
    'PbApp\Address'=>[
        'IphoneNum'=>[
            'IsScalarType'=>true,
            'FieldType'=>'string', 
            'IsArray'=>false, 
            'IsMap'=>false, 
            'MapKeyType'=>'null'
        ],

        'Gender'=>[
            'IsScalarType'=>true,
            'FieldType'=>'string', 
            'IsArray'=>false, 
            'IsMap'=>false, 
            'MapKeyType'=>'null'
        ],
    ],
    'PbApp\City'=>[
        'Name'=>[
            'IsScalarType'=>true,
            'FieldType'=>'string', 
            'IsArray'=>false, 
            'IsMap'=>false, 
            'MapKeyType'=>'null'
        ],
    ],
    'PbApp\UserLoginACK'=>[
        'UserInfo'=>[
            'IsScalarType'=>false,
            'FieldType'=>'PbApp\UserInfo', 
            'IsArray'=>false, 
            'IsMap'=>false, 
            'MapKeyType'=>'null'
        ],

        'AddrList'=>[
            'IsScalarType'=>false,
            'FieldType'=>'PbApp\Address', 
            'IsArray'=>false, 
            'IsMap'=>true, 
            'MapKeyType'=>'string'
        ],

        'GoneCities'=>[
            'IsScalarType'=>false,
            'FieldType'=>'PbApp\City', 
            'IsArray'=>true, 
            'IsMap'=>false, 
            'MapKeyType'=>'null'
        ],
    ],
];