<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg.proto

namespace PbApp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>PbApp.Address</code>
 */
class Address extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string IphoneNum = 1;</code>
     */
    private $IphoneNum = '';
    /**
     * Generated from protobuf field <code>string Gender = 2;</code>
     */
    private $Gender = '';

    public function __construct() {
        \GPBMetadata\Msg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string IphoneNum = 1;</code>
     * @return string
     */
    public function getIphoneNum()
    {
        return $this->IphoneNum;
    }

    /**
     * Generated from protobuf field <code>string IphoneNum = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setIphoneNum($var)
    {
        GPBUtil::checkString($var, True);
        $this->IphoneNum = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Gender = 2;</code>
     * @return string
     */
    public function getGender()
    {
        return $this->Gender;
    }

    /**
     * Generated from protobuf field <code>string Gender = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setGender($var)
    {
        GPBUtil::checkString($var, True);
        $this->Gender = $var;

        return $this;
    }

}

