<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg.proto

namespace PbApp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>PbApp.Meta</code>
 */
class Meta extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 Param1 = 1;</code>
     */
    private $Param1 = 0;

    public function __construct() {
        \GPBMetadata\Msg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int32 Param1 = 1;</code>
     * @return int
     */
    public function getParam1()
    {
        return $this->Param1;
    }

    /**
     * Generated from protobuf field <code>int32 Param1 = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setParam1($var)
    {
        GPBUtil::checkInt32($var);
        $this->Param1 = $var;

        return $this;
    }

}

