<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg.proto

namespace PbApp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>PbApp.Request</code>
 */
class Request extends \Google\Protobuf\Internal\Message
{
    /**
     * 消息头
     *
     * Generated from protobuf field <code>map<string, string> Headers = 1;</code>
     */
    private $Headers;
    /**
     * 具体参数字典
     *
     * Generated from protobuf field <code>map<string, string> BodyParams = 2;</code>
     */
    private $BodyParams;

    public function __construct() {
        \GPBMetadata\Msg::initOnce();
        parent::__construct();
    }

    /**
     * 消息头
     *
     * Generated from protobuf field <code>map<string, string> Headers = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getHeaders()
    {
        return $this->Headers;
    }

    /**
     * 消息头
     *
     * Generated from protobuf field <code>map<string, string> Headers = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setHeaders($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->Headers = $arr;

        return $this;
    }

    /**
     * 具体参数字典
     *
     * Generated from protobuf field <code>map<string, string> BodyParams = 2;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getBodyParams()
    {
        return $this->BodyParams;
    }

    /**
     * 具体参数字典
     *
     * Generated from protobuf field <code>map<string, string> BodyParams = 2;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setBodyParams($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->BodyParams = $arr;

        return $this;
    }

}

