<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg.proto

namespace PbApp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>PbApp.UserInfo</code>
 */
class UserInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string OpenUid = 1;</code>
     */
    private $OpenUid = '';
    /**
     * Generated from protobuf field <code>string NickName = 2;</code>
     */
    private $NickName = '';

    public function __construct() {
        \GPBMetadata\Msg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string OpenUid = 1;</code>
     * @return string
     */
    public function getOpenUid()
    {
        return $this->OpenUid;
    }

    /**
     * Generated from protobuf field <code>string OpenUid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOpenUid($var)
    {
        GPBUtil::checkString($var, True);
        $this->OpenUid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string NickName = 2;</code>
     * @return string
     */
    public function getNickName()
    {
        return $this->NickName;
    }

    /**
     * Generated from protobuf field <code>string NickName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNickName($var)
    {
        GPBUtil::checkString($var, True);
        $this->NickName = $var;

        return $this;
    }

}

