<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg.proto

namespace PbApp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>PbApp.UserLoginACK</code>
 */
class UserLoginACK extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.PbApp.UserInfo UserInfo = 1;</code>
     */
    private $UserInfo = null;
    /**
     * Generated from protobuf field <code>map<string, .PbApp.Address> AddrList = 2;</code>
     */
    private $AddrList;
    /**
     * Generated from protobuf field <code>repeated .PbApp.City GoneCities = 3;</code>
     */
    private $GoneCities;

    public function __construct() {
        \GPBMetadata\Msg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.PbApp.UserInfo UserInfo = 1;</code>
     * @return \PbApp\UserInfo
     */
    public function getUserInfo()
    {
        return $this->UserInfo;
    }

    /**
     * Generated from protobuf field <code>.PbApp.UserInfo UserInfo = 1;</code>
     * @param \PbApp\UserInfo $var
     * @return $this
     */
    public function setUserInfo($var)
    {
        GPBUtil::checkMessage($var, \PbApp\UserInfo::class);
        $this->UserInfo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, .PbApp.Address> AddrList = 2;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getAddrList()
    {
        return $this->AddrList;
    }

    /**
     * Generated from protobuf field <code>map<string, .PbApp.Address> AddrList = 2;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setAddrList($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \PbApp\Address::class);
        $this->AddrList = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .PbApp.City GoneCities = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGoneCities()
    {
        return $this->GoneCities;
    }

    /**
     * Generated from protobuf field <code>repeated .PbApp.City GoneCities = 3;</code>
     * @param \PbApp\City[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGoneCities($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \PbApp\City::class);
        $this->GoneCities = $arr;

        return $this;
    }

}

