<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg.proto

namespace PbApp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>PbApp.UserInfo</code>
 */
class UserInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string OpenUid = 1;</code>
     */
    private $OpenUid = '';
    /**
     * Generated from protobuf field <code>string NickName = 2;</code>
     */
    private $NickName = '';
    /**
     * Generated from protobuf field <code>int32 Age = 3;</code>
     */
    private $Age = 0;
    /**
     * Generated from protobuf field <code>int32 Param1 = 4;</code>
     */
    private $Param1 = 0;

    public function __construct() {
        \GPBMetadata\Msg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string OpenUid = 1;</code>
     * @return string
     */
    public function getOpenUid()
    {
        return $this->OpenUid;
    }

    /**
     * Generated from protobuf field <code>string OpenUid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOpenUid($var)
    {
        GPBUtil::checkString($var, True);
        $this->OpenUid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string NickName = 2;</code>
     * @return string
     */
    public function getNickName()
    {
        return $this->NickName;
    }

    /**
     * Generated from protobuf field <code>string NickName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNickName($var)
    {
        GPBUtil::checkString($var, True);
        $this->NickName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Age = 3;</code>
     * @return int
     */
    public function getAge()
    {
        return $this->Age;
    }

    /**
     * Generated from protobuf field <code>int32 Age = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setAge($var)
    {
        GPBUtil::checkInt32($var);
        $this->Age = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Param1 = 4;</code>
     * @return int
     */
    public function getParam1()
    {
        return $this->Param1;
    }

    /**
     * Generated from protobuf field <code>int32 Param1 = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setParam1($var)
    {
        GPBUtil::checkInt32($var);
        $this->Param1 = $var;

        return $this;
    }

}

