<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg.proto

namespace PbApp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>PbApp.UserMsgLoginREQ</code>
 */
class UserMsgLoginREQ extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string UserName = 1;</code>
     */
    private $UserName = '';
    /**
     * Generated from protobuf field <code>string Password = 2;</code>
     */
    private $Password = '';

    public function __construct() {
        \GPBMetadata\Msg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string UserName = 1;</code>
     * @return string
     */
    public function getUserName()
    {
        return $this->UserName;
    }

    /**
     * Generated from protobuf field <code>string UserName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUserName($var)
    {
        GPBUtil::checkString($var, True);
        $this->UserName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Password = 2;</code>
     * @return string
     */
    public function getPassword()
    {
        return $this->Password;
    }

    /**
     * Generated from protobuf field <code>string Password = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->Password = $var;

        return $this;
    }

}

